<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ActiviteMission extends Model
{

    use Sluggable;
    use SoftDeletes;

    protected $fillable = [
        'activite_id',
        'dossier_medical_id',
        'creator',
        'commentaire',
        'description',
        'nom_partenaire',
        'nom_activite',
        'statut',
        'date_cloture',
        'slug',
    ];


    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'DossierAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        ActiviteMission::creating(function ($activite){
            $activite->creator = Auth::id();
        });

    }

    public function getDossierAndTimestampAttribute() {
        return Str::random(10) . ' ' .Carbon::now()->timestamp;
    }

    public function activite(){
        return $this->belongsTo(Activite::class,'activite_id','id');
    }

    public function createur(){
        return $this->belongsTo(User::class,'creator','id');
    }

    public function dossier(){
        return $this->belongsTo(DossierMedical::class,'dossier_medical_id','id');
    }

    public function description(){
        return $this->belongsTo(GroupeActiviteMission::class,'description','id');
    }
}
