<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Support\Str;
use App\Models\LigneDeTemps;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use App\Models\ActivitesMedecinReferent;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;

class ActivitesControle extends Model
{
    use Sluggable;
    use SoftDeletes;

    protected $table = 'activites_controle';
    protected $fillable = [
        "activite_id",
        "patient_id",
        'etablissement_id',
        'affiliation_id',
        'ligne_temps_id',
        "creator",
        "commentaire",
        "statut",
        "date_cloture",
        "slug",
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'DossierAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        ActivitesControle::creating(function ($med){
            $med->creator = Auth::id();
        });

    }

    public function getDossierAndTimestampAttribute() {
        return Str::random(10) . ' ' .Carbon::now()->timestamp;
    }

    public function activitesMedecinReferent(){
        return $this->belongsTo(ActivitesMedecinReferent::class,'activite_id','id');
    }

    public function createur(){
        return $this->belongsTo(User::class,'creator','id');
    }

    public function patient(){
        return $this->belongsTo(Patient::class,'patient_id','user_id');
    }

    public function updatedBy(){
        return $this->belongsTo(User::class,'updated_by','id');
    }

    public function ligne_temps(){
        return $this->belongsTo(LigneDeTemps::class);
    }

    public function affiliation(){
        return $this->belongsTo(Affiliation::class);
    }

    public function motif(){
        return $this->belongsTo(Motif::class);
    }
    public function etablissement(){
        return $this->belongsTo(EtablissementExercice::class, 'etablissement_id');
    }

}
