<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class CategoriePrestation extends Model
{
    use Sluggable;
    use SoftDeletes;

    protected $fillable = ['nom','slug'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(5).' '.Carbon::now()->timestamp;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Suivi::creating(function ($categorie){
            $categorie->creator = Auth::id();
        });

    }

    public function prestations(){
        return $this->hasMany(Prestation::class,'categorie_id','id');
    }
}
