<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class EtablissementPrestation extends Model
{
    use Sluggable;
    use SoftDeletes;

    protected $table = 'etablissement_prestation';
    protected $fillable = [
        'etablissement_id',
        'prestation_id',
        'prix',
        'reduction',
        'slug'
    ];


    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Suivi::creating(function ($prestation){
            $prestation->creator = Auth::id();
        });

    }

    public function getNameAndTimestampAttribute() {
        return Str::random(5).' '.Carbon::now()->timestamp;
    }

    public function prestation(){
        return $this->belongsTo(Prestation::class,'prestation_id','id');
    }

    public function etablissement(){
        return $this->belongsTo(EtablissementExercice::class,'etablissement_id','id');
    }
}
