<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * App\Models\FacturePrestation
 *
 * @property int $id
 * @property int $facture_id
 * @property int $prestation_id
 * @property int|null $creator
 * @property string|null $date_prestation
 * @property string $slug
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property string $statut
 * @property string|null $motif
 * @property-read \App\Models\Facture $facture
 * @property-read mixed $name_and_timestamp
 * @property-read \App\Models\EtablissementPrestation $prestation_etablissement
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation findSimilarSlugs($attribute, $config, $slug)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation newQuery()
 * @method static \Illuminate\Database\Query\Builder|FacturePrestation onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation query()
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereCreator($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereDatePrestation($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereFactureId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereMotif($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation wherePrestationId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereStatut($value)
 * @method static \Illuminate\Database\Eloquent\Builder|FacturePrestation whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|FacturePrestation withTrashed()
 * @method static \Illuminate\Database\Query\Builder|FacturePrestation withoutTrashed()
 * @mixin \Eloquent
 */
class FacturePrestation extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = [
        "facture_id",
        "prestation_id",
        "date_prestation",
        "statut",
        "motif",
        "slug",
        "creator",
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //On définit le créateur à la création du suivi
        Suivi::creating(function ($prestation){
            $prestation->creator = Auth::id();
        });
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(16).' '.Carbon::now()->timestamp;
    }

    public function facture(){
        return $this->belongsTo(Facture::class,'facture_id','id');
    }

    public function prestation_etablissement(){
        return $this->belongsTo(EtablissementPrestation::class,'prestation_id','id');
    }
}
