<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Facture extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = [
        'dossier_medical_id',
        'etablissement_id',
        'creator',
        'total_hors_remise',
        'total_avec_remise',
        'date_facturation',
        'motif',
        'statut',
        'remise',
        'slug',
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //On définit le créateur à la création du suivi
        Suivi::creating(function ($facture){
            $facture->creator = Auth::id();
        });
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(16).' '.Carbon::now()->timestamp;
    }

    public function dossier(){
        return $this->belongsTo(DossierMedical::class,'dossier_medical_id','id');
    }

    public function createur(){
        return $this->belongsTo(User::class,'creator','id');
    }

    public function files(){
        return $this->morphMany(File::class,'fileable');
    }

    public function etablissement(){
        return $this->belongsTo(EtablissementExercice::class,'etablissement_id','id');
    }

    public function prestations(){
        return $this->hasMany(FacturePrestation::class,'facture_id','id');
    }
}
