<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class FactureAvisDetail extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = [
        "facture_avis_id",
        "medecin_avis_id",
        "total_montant",
        "medicasure_montant",
        "association_montant",
        "medecin_avis_montant",
        "slug",
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //On définit le créateur à la création du suivi
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(16).' '.Carbon::now()->timestamp;
    }

    public function medecinAvis(){
        return $this->belongsTo(MedecinAvis::class,'medecin_avis_id','id');
    }

    public function factureAvis(){
        return $this->belongsTo(factureAvis::class,'facture_avis_id','id');
    }

    public function etablissement(){
        return $this->belongsTo(EtablissementExercice::class,'etablissement_id','id');
    }
}