<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class FacturePrestation extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = [
        "facture_id",
        "prestation_id",
        "date_prestation",
        "slug",
        "creator",
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //On définit le créateur à la création du suivi
        Suivi::creating(function ($prestation){
            $prestation->creator = Auth::id();
        });
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(16).' '.Carbon::now()->timestamp;
    }

    public function facture(){
        return $this->belongsTo(Facture::class,'facture_id','id');
    }

    public function prestation_etablissement(){
        return $this->belongsTo(EtablissementPrestation::class,'prestation_id','id');
    }
}
