<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Prestation extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = ['nom','slug','prix','categorie_id'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(5).' '.Carbon::now()->timestamp;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Prestation::creating(function ($prestation){
            $prestation->creator = Auth::id();
        });

    }

    public function categorie(){
        return $this->belongsTo(CategoriePrestation::class,'categorie_id','id');
    }
}
