<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Suivi extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = [
        "dossier_medical_id",
        "responsable",
        "motifs",
        "slug",
        "etat",
        "creator",
        'categorie_id'
    ];

    protected $hidden = [
        'deleted_at',
        'updated_at'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'NameAndTimestamp'
            ]
        ];
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //On définit le créateur à la création du suivi
        Suivi::creating(function ($suivi){
            $suivi->creator = Auth::id();
        });
    }

    public function getNameAndTimestampAttribute() {
        return Str::random(16).' '.Carbon::now()->timestamp;
    }

    public function dossier(){
        return $this->belongsTo(DossierMedical::class,'dossier_medical_id','id');
    }

    public function createur(){
        return $this->belongsTo(User::class,'creator','id');
    }

    public function responsable(){
        return $this->belongsTo(User::class,'responsable','id');
    }

    public function specialites(){
        return $this->hasMany(SpecialiteSuivi::class,'suivi_id','id');
    }

    public function categorie(){
        return $this->belongsTo(Categories::class,'categorie_id','id');
    }
}
