<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use App\Models\Praticien;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\TimeActivite
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $date
 * @property string|null $start
 * @property string|null $stop
 * @property string $slug
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read mixed $dossier_and_timestamp
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite findSimilarSlugs($attribute, $config, $slug)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite newQuery()
 * @method static \Illuminate\Database\Query\Builder|TimeActivite onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite query()
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereStart($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereStop($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|TimeActivite whereUserId($value)
 * @method static \Illuminate\Database\Query\Builder|TimeActivite withTrashed()
 * @method static \Illuminate\Database\Query\Builder|TimeActivite withoutTrashed()
 * @mixin \Eloquent
 */
class TimeActivite extends Model
{
    use Sluggable;
    use SoftDeletes;

    protected $fillable = [
        'user_id',
        'date',
        'start',
        'stop',
        'slug',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'DossierAndTimestamp'
            ]
        ];
    }

    public function getDossierAndTimestampAttribute() {
        return Str::random(10) . ' ' .Carbon::now()->timestamp;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        TimeActivite::creating(function ($time){
            $time->user_id = Auth::id();
        });
    }

    public function time(){
        return $this->hasMany(TimeActivite::class, 'user_id', 'praticien_id');
    }

    public function user(){
        return $this->belongsTo(Praticien::class,'user_id','user_id');
    }
}
